services:
  - type: web
    name: flaskr
    autoDeploy: true # optional
    env: python
    repo: https://github.com/Adorism/flaskrtutorial
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:gunicorn_app"
    initialDeployHook: poetry run flask init-db
    envVars:
      - key: FLASK_APP
        value: flaskr
      - key: FLASK_DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.9.1