services:
  - type: web
    name: flasktut
    autoDeploy: true # optional
    env: python
    repo: https://github.com/Adorism/flaskrtutorial
    buildCommand: /opt/render/project/src/.venv/bin/python -m pip install --upgrade pip && poetry install
    startCommand: poetry run flask run
    initialDeployHook: poetry run flask init-db
    envVars:
      - key: FLASK_APP
        value: flaskr
      - key: FLASK_DEBUG
        value: true
      - key: PYTHON_VERSION
        value: 3.8.1